# Generated by Django 3.2.7 on 2022-01-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitemmodel_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemmodel',
            name='is_available',
        ),
    ]
