# Generated by Django 3.2.7 on 2022-01-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitemmodel_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
