# Generated by Django 3.2.7 on 2022-01-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variationmodel'),
        ('cart', '0005_cartitemmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.VariationModel'),
        ),
    ]
