# Generated by Django 3.2.7 on 2022-01-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payment'},
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
