# Generated by Django 3.2.7 on 2022-02-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220208_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductmodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproductmodel',
            name='size',
        ),
    ]
