# Generated by Django 3.2.7 on 2022-02-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variationmodel'),
        ('orders', '0004_auto_20220208_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductmodel',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproductmodel',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.VariationModel'),
        ),
    ]
