# Generated by Django 3.2.7 on 2022-02-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220208_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproductmodel',
            options={'verbose_name': 'Order Product', 'verbose_name_plural': 'Order Products'},
        ),
    ]
